AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Live passthrough weather
Globals:
  Function:
    Runtime: python3.10
    Timeout: 10
    MemorySize: 256

Parameters:
  SecretName:
    Type: String
    Default: /api-key

Resources:
  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: reader/
      Handler: app.handler
      Environment:
        Variables:
          SECRET_NAME: !Ref SecretName
      Policies:
        - Statement:
            Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*
      Events:
        HttpGetWeather:
          Type: HttpApi
          Properties:
            Path: /weather
            Method: GET

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
    Description: Base URL for the HTTP API
